dist: xenial
language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7
matrix:
  allow_failures:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
cache:
- pip
- apt
install:
- pip install pipenv
- pipenv install --dev --skip-lock --python `which python`
- pipenv graph
script:
- pipenv run py.test -vv --cov=pypfb --cov-report xml tests
- pipenv run python th_wrapper.py -w truffles.json -c thog_config.json -g file:///${PWD}/ --check
after_script:
- pipenv run python-codacy-coverage -r coverage.xml
before_deploy:
- sed -i.bak "s/=get_version()/='$TRAVIS_TAG'/g" setup.py
- cat setup.py
- if [ $(python setup.py --version) == '0.0.0' ]; then travis_terminate 1; fi
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    python: 2.7
    repo: uc-cdis/pypfb
    tags: true
after_deploy:
- pipenv run gen3git release
env:
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1
