[tool.poetry]
name = "pfb"
version = "0.1.0"
description = ""
authors = ["CTDS UChicago <cdis@uchicago.edu>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
codacy-coverage = "*"
pytest = "~=3.2"
pytest-cov = "~=2.5"
truffleHog = "*"
gen3git = "*"
more-itertools = "~=5.0"
click = "~=7.0"
fastavro = ">=0.21"
python-json-logger = "~=0.1"
PyYAML = "~=5.1"
dictionaryutils = ">=3.0.2"
gdcdictionary = ">=1.2.0"



[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
